### ISSUE TITLE
Возможность сброса карт

### ISSUE THREAD

**Issue by Djaler** [adjsky/evil-cards#97]
Есть вот такая возможность в [правилах](https://www.mosigra.ru/image/data/mosigra.product.other/560/938/500zlcd_rules.pdf):
`Любой игрок может в любой момент потратить одну
из заработанных плюшек на обмен карт: он должен сбросить
все карты из своей руки и набрать новые 10 карт из белой
стопки.`

Очень полезно бывает, если выпали сильно неудачные карты, которые не получается куда-то приткнуть

**Comment by adjsky** [comment]
Спасибо за предложение, учту и реализую в следующих обновлениях :)
